language: csharp
solution: QuantConnect.Lean.sln
install:
  - nuget restore QuantConnect.Lean.sln
  - nuget install NUnit.Runners -Version 2.6.4 -OutputDirectory testrunner
script:
  - chmod 777 /home/travis/build/QuantConnect/Lean/Algorithm.Java/build.sh
  - xbuild /p:Configuration=Release /p:VbcToolExe=vbnc.exe QuantConnect.Lean.sln
  - mono ./testrunner/NUnit.Runners.2.6.4/tools/nunit-console.exe ./Tests/bin/Release/QuantConnect.Tests.dll